import {
  faEnvelope,
  faGear,
  faBell,
  faMoon,
  faSun,
  faPlus,
  faXmark,
  faCheck,
  faTrashCan,
  faPenToSquare,
  faPaperPlane,
  faSpinner,
  faInbox,
  faCirclePause,
  faCircleCheck,
  faCircleExclamation,
  faCircleInfo,
  faKey,
  faSliders,
  faClock,
  faBars,
  faChartLine,
  faTriangleExclamation,
  faGaugeHigh,
  faFileLines,
  faChevronDown,
  faMemory,
  faPalette,
} from "@fortawesome/free-solid-svg-icons"
import type { IconDefinition } from "@fortawesome/fontawesome-svg-core"

export const icons = {
  email: faEnvelope,
  settings: faGear,
  bell: faBell,
  moon: faMoon,
  sun: faSun,
  plus: faPlus,
  close: faXmark,
  check: faCheck,
  delete: faTrashCan,
  edit: faPenToSquare,
  send: faPaperPlane,
  spinner: faSpinner,
  inbox: faInbox,
  pause: faCirclePause,
  success: faCircleCheck,
  error: faCircleExclamation,
  info: faCircleInfo,
  key: faKey,
  parameters: faSliders,
  clock: faClock,
  menu: faBars,
  stats: faChartLine,
  warning: faTriangleExclamation,
  gauge: faGaugeHigh,
  logs: faFileLines,
  chevron: faChevronDown,
  memory: faMemory,
  themes: faPalette,
} satisfies Record<string, IconDefinition>

export type IconName = keyof typeof icons
